### ISSUE TITLE
2.0 

### ISSUE THREAD

**Issue by dy** [dy/wavefont#16]
* [x] variable axis: width #15  via designfile
* [x] feature-file with [GPOS 8](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6h-gpos-lookuptype-8-chaining-contextual-positioning) positioning marks #2
* [x] ~~proper hints without subpixel gaps (psautohint?) #3 ~~ impossible
* [x] all checks passed
* [x] windows-able to install/use #13 
* [x] proper handling of clipping #7 
* [x] better demo

**Comment by dy** [comment]
See separate issues.
