### ISSUE TITLE
3.0 improvements needed

### ISSUE THREAD

**Issue by dy** [dy/wavefont#38]
* [x] More up/down shifts via accents, at least till 50.
* [x] Latin-Ext range for Low-align, Cyrillic range for Center-align, see https://github.com/dy/wavefont/issues/21#issuecomment-1125571928 for argumentation
* [x] Latin/ASCII cover 52 chars - it seems to be very natural expectation.
* [x] ~~Embed last-resort [blank font](https://github.com/adobe-fonts/adobe-blank-vf) into wavefont to avoid CSS fallback.~~ faster to have sync fallback and build wavefont upon it.
* [x] WGHT and WDTH are useful as separate properties. Unlike tracking, WDTH stabilizes advance width as absolute value, so weight can safely be changed within the allocated stride. 
* [x] char should be left-aligned within width, not center-aligned.
* [x] Map axes to standardized names - SOFT.
* [x] ~~pass fontbakery tests #14 ~~
* [x] +-10 y-shift accents #19 
* [x] expose meaningful JS API
* [x] ~~demo with painter #27 ~~
* [x] Limit weight to 400 (no sense to have it too big, besides that's standard value for Google Fonts).
